ocp = Model(variable=true)
variable!(ocp, 1)
time!(ocp, t0=0, indf=1)
state!(ocp, 2)
control!(ocp, 1)
constraint!(ocp, :control, lb=-1, ub=1)
constraint!(ocp, :initial, lb=[0,0], ub=[0,0])
constraint!(ocp, :final, lb=[1,0], ub=[1,0])
constraint!(ocp, :variable, lb=0.1, ub=Inf)
dynamics!(ocp, (x, u, v) ->  [x[2], u])
objective!(ocp, :mayer, (x0, xf, v) -> v)