ocp = Model(variable=true)
variable!(ocp, 1)
time!(ocp, 0, Index(1))
state!(ocp, 2)
control!(ocp, 1)
constraint!(ocp, :control, -1, 1, :control_constraint)
constraint!(ocp, :initial, [0,0], :initial_constraint)
constraint!(ocp, :final, [1,0], :final_constraint)
constraint!(ocp, :variable, 0.1, Inf, :variable_constraint)
dynamics!(ocp, (x, u, v) ->  [x[2], u])
objective!(ocp, :mayer, (x0, xf, v) -> v)